url = "https://www.youtube.com/watch?v=ferZnZ0_rSM"
artist = "Anderson .Paak & The Free Nationals"
title = "NPR Music Tiny Desk Concert"
date = "2016-08-22"
tracks = [
    { time = "00:00", name = "Come Down" },
    { time = "03:03" },
    { time = "03:44", name = "Heart Don't Stand A Chance" },
    { time = "06:49" },
    { time = "07:33", name = "Put Me Thru" },
    { time = "10:40" },
    { time = "11:57", name = "Suede" },
    { time = "15:05" },
]
