url = "https://www.youtube.com/watch?v=ferZnZ0_rSM"
artist = "Anderson .Paak & The Free Nationals"
title = "NPR Music Tiny Desk Concert"
date = "2016-08-22"
tracks = [
    { start = "00:00", end = "03:03", name = "Come Down" },
    { start = "03:44", end = "06:49", name = "Heart Don't Stand A Chance" },
    { start = "07:33", end = "10:40", name = "Put Me Thru" },
    { start = "11:57", end = "15:05", name = "Suede" },
]
