url = "https://www.youtube.com/watch?v=N1w-hDiJ4dM"
title = "Tyler, The Creator: NPR Music Tiny Desk Concert"
date = "2017-12-14"
tracks = [
    { time = "00:00", name = "Boredom" },
    { time = "07:00" },
    { time = "08:36", name = "See You Again" },
    { time = "12:23" },
    { time = "13:12", name = "Glitter" },
    { time = "19:00" },
]
