url = "https://www.youtube.com/watch?v=wMehItNQKAA"
artist = "IDLES"
title = "NPR Music Tiny Desk Concert"
date = "2019-06-26"
tracks = [
    { start = "00:00", end = "04:14", name = "Never Fight A Man With A Perm" },
    { start = "04:35", end = "08:12", name = "Mercedes Marxist" },
    { start = "08:46", end = "12:47", name = "I'm Scum" },
]
