url = "https://www.youtube.com/watch?v=jnm2Lf1TiB4"
title = "Malcriada - Full Performance (Live on KEXP)"
date = "June 17, 2026"
tracks = [
    { time = "00:55", name = "Under" },
    { time = "03:37", name = "Six Seven" },
    { time = "06:33", name = "Acid Lover" },
    { time = "10:29", name = "Miénteme" },
]
